import { FastifyInstance } from 'fastify';
import { buildApp } from '../../app';

/**
 * Builds the application purely to read its API contract, with no database attached.
 *
 * One builder shared by the emitter and by the coverage test, so what CI lints and what the test
 * asserts are the same document. Two producers of "the spec" is how a document drifts from the
 * service it describes.
 */

export interface OpenApiDocument {
  openapi: string;
  info: { title: string; version: string; description?: string };
  paths?: Record<string, Record<string, OpenApiOperation>>;
  components?: { schemas?: Record<string, unknown>; securitySchemes?: Record<string, unknown> };
  tags?: Array<{ name: string; description?: string }>;
}

export interface OpenApiOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  tags?: string[];
  security?: Array<Record<string, string[]>>;
  parameters?: unknown[];
  requestBody?: unknown;
  responses?: Record<string, { description?: string; content?: Record<string, { schema?: unknown; example?: unknown; examples?: unknown }> }>;
}

export interface RegisteredRoute {
  method: string;
  url: string;
}

/** The HTTP methods an operation can be documented under. HEAD and OPTIONS are generated by Fastify. */
export const DOCUMENTED_METHODS = ['get', 'put', 'post', 'delete', 'patch'] as const;

/** Routes Fastify or a plugin registers that are not part of anyone's contract. */
export function isContractRoute(route: RegisteredRoute): boolean {
  if (route.method === 'HEAD' || route.method === 'OPTIONS') return false;
  // The documentation UI serves itself and its own assets.
  if (route.url === '/doc' || route.url.startsWith('/doc/')) return false;
  return true;
}

/** Fastify's `/users/:id` against OpenAPI's `/users/{id}`. */
export function toOpenApiPath(url: string): string {
  return url.replace(/:([A-Za-z0-9_]+)/g, '{$1}').replace(/\/\*$/, '/{wildcard}');
}

export async function buildOpenApiApp(): Promise<{
  app: FastifyInstance;
  document: OpenApiDocument;
  routes: RegisteredRoute[];
}> {
  const app = await buildApp({ skipDatabase: true });
  await app.ready();

  // The application's own list, collected by an onRoute hook installed before any module registers.
  // Reading Fastify's printed tree instead would mean parsing a display format, and a change in that
  // format would silently empty the list and make the coverage check pass by finding nothing.
  const routes = [...app.registeredRoutes];
  const document = app.swagger() as unknown as OpenApiDocument;
  return { app, document, routes };
}
